name: Fetch vaccination stats
on:
  schedule:
    - cron: "0 * * * *"
    # - cron: "0 9 * * *"

jobs:
  build:
    name: Fetch vaccination stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
