name: A workflow for my Hello World file
on:
  schedule:
    - cron: "0 * * * *"
    # - cron: "0 9 * * *"

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
