name: Fetch vaccination stats
on:
  schedule:
    - cron: "*/5 * * * *"
    # - "cron: 0 8 * * *"

jobs:
  build:
    name: Fetch vaccination stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
